Description: >
  Just Me / Udacity 2019

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

  # IAM Role to allow EC2 Session Manager to access our server
  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - 'sts:AssumeRole'

  # Instance Profile
  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - !Ref RoleForSSMAccess

  # Security Group
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our host
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  # Server EC2 Instance
  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07df274a488ca9195 # Amazon Linux x86 ami for eu-central-1
      InstanceType: t2.micro
      IamInstanceProfile: !Ref ServerInstanceProfile
      SecurityGroupIds:
      - Ref: WebAccessSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub "${EnvironmentName}-PRI-SN"
