AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Just me / Udacity

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  UserName:
    Description: User name for the DB instance
    Type: String

  Password:
    Description: Password for the DB instance
    Type: String

  SubnetGroupIds:
    Description: Subnet group ids for the db
    Type: CommaDelimitedList

  SecurityGroupIds:
    Description: Security group ids for the db
    Type: CommaDelimitedList

Resources:

  MyDBSubnetGroup1:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for MyDB
      SubnetIds: !Ref SubnetGroupIds

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.small
      DBSubnetGroupName: !Ref MyDBSubnetGroup1
      PubliclyAccessible: false
      MultiAZ: false
      AllocatedStorage: 20
      Engine: mysql
      MasterUsername: !Sub "${UserName}"
      MasterUserPassword: !Sub "${Password}"
      VPCSecurityGroups: !Ref SecurityGroupIds
      Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName} MS SQL RDS"
    #DeletionPolicy: Retain
